@baseUrl = http://localhost:3333

GET {{baseUrl}}/ HTTP/1.1

### Register
POST {{baseUrl}}/register HTTP/1.1
Content-Type: application/json

{
    "email": "admin4@gmail.com",
    "name": "testuser1",
    "password": "testp",
    "confirmpassword": "testp"
}

### Login
# @name login
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "testpassword"
}

### Secure Route

@authtoken = {{login.response.body.token}}
GET {{baseUrl}}/me HTTP/1.1
Authorization: Bearer {{authtoken}}